### ISSUE TITLE
Automatiser les migrations de données lors des déploiements

### ISSUE THREAD

**Issue by JeromeBu** [codegouvfr/sill#104]
## Situation actuelle

Actuellement les migrations de données lors des changements de modèle sont effectuées avec des scripts lancés manuellement (@garronej  dis-moi si je me trompe).

## Problème

Avec la possibilité de déployer l'application ailleurs que juste sur le SILL, cela signifie qu'on aura certainement pas accès aux repos de data des autres instances que celle du SILL. Et donc on ne pourra pas jouer de scripts manuels qui touchent ces repos. 

## Propositions

1. Il faudrait envisager de développer un système du même type que les ceux utilisés pour les migrations de DB SQL. Avec un fichier par migration, et dans la DB un json qui listerait les migrations déjà joués. À chaque déploiement, il y aurait un check pour voir si certaines migrations n'ont pas encore été jouées, et les jouerait si nécessaire. 

2. L'autre option est d'attendre, car si nous envisageons de changer le système de stockage vers une base postgresSQL, les outils de migrations seront directement disponibles (packages npm et autre...). Ca dépendra de la priorité de  #101

**Comment by bzg** [comment]
Il me semble qu'on peut désormais fermer cette issue.  @JeromeBu ?

**Comment by JeromeBu** [comment]
Issue traité avec le passage à Postgres
