### ISSUE TITLE
Modifier le fonctionnement de la redirection de `sill.code.gouv.fr` vers `code.gouv.fr/sill`

### ISSUE THREAD

**Issue by JeromeBu** [codegouvfr/sill#107]
Actuellement : `sill.code.gouv.fr` pointe vers le sspcloud

Et il y a une app qui redirige de `sill.code.gouv.fr` vers `code.gouv.fr/sill`

Ça n'est pas souhaitable d'avoir une app pour ça. On devrait faire cette redirection directement dans le nginx du codegouv

Il faut donc : 

1. Mettre à jour les DNS
2. Mettre à jour la config nginx (en conservant les paths des urls)

Pour info le liens vers https://github.com/codegouvfr/paris-sspcloud

**Comment by bzg** [comment]
J'ai demandé la mise à jour des DNS et mis à jour la config nginx, c'est OK.

**Comment by garronej** [comment]
Great! 👍🏻
