### ISSUE TITLE
Présenter tous les champs necessaires pour HAL

### ISSUE THREAD

**Issue by JeromeBu** [codegouvfr/sill#124]
Exemple de fiche HAL correctement renseignée : https://inria.hal.science/hal-04056972v1
Puis cliquer sur : `List complète des metadonnées`
Les données à présenter sont : tout ce qui apparait dans la liste des metadonnées, sauf `Format du dépot` et `type de document`

La présentation se fera sur la page de détails d'un logiciel : exemple : https://code.gouv.fr/sill/detail?name=Git

### Infos à voir : 
- Celles des meta-données (précisée ci-dessus)

### Infos à remplacer : 
- Date d'ajout devient -> Date de dernière mise à jour (c'est à dire que le logiciel était différent de la valeur du précédent moissonnage).
- Liens utiles ->
      - le lien vers HAL
      - le lien vers software heritage (le SWHID)

### Infos à ne pas voir : 
- Les prérogatives

## Les onglets

- On va conserver l'onglet `Aperçu`
- On supprime l'onglet `Prestataire de services`
- On supprime l'onglet `Logiciel similaires` ( pour l'instant) 

Dans cette issue, on ne va pas récupérer le détails des auteurs, ça sera le sujet d'une issue séparée

**Comment by guillermau** [comment]
Données intéressantes à récupéer
* Keywords
* Domains
* Software metadata
* Organization / institution
* Language

UI
* Attention aux liens vers wikidata
* Pas de logo

**Comment by JeromeBu** [comment]
On a besoin de #166 avant de pouvoir faire celle ci
