### ISSUE TITLE
Certains prestataires n'apparaissent pas dans l'onglet "Prestataires de services"

### ISSUE THREAD

**Issue by Sup3rM1kr0** [codegouvfr/sill#126]
Certains prestataires n'apparaissent pas dans l'onglet "prestataires de services".

Exemple : [GitLab Community Edition](https://code.gouv.fr/sill/detail?name=GitLab%20Community%20Edition)

La société Bearstech n'apparaît pas alors qu'elle est bien référencée sur le site Comptoir du Libre : [Bearstech sur Comptoir du Libre](https://comptoir-du-libre.org/fr/softwares/198)

**Comment by dzc34** [comment]
> Exemple : GitLab Community Edition
> 
> La société Bearstech n'apparaît pas alors qu'elle est bien référencée sur le site Comptoir du Libre : Bearstech sur Comptoir du Libre

Précision : la société Bearstech est bien associé à Gitlab depuis le 16/04/2024 sur le Comptoir du Libre.

voir : https://www.data.gouv.fr/fr/datasets/logiciels-libres-sur-le-comptoir-du-libre-org/

![Screenshot 2024-06-17 at 13-33-06 https __comptoir-du-libre org](https://github.com/codegouvfr/sill/assets/6709977/8478878b-ad18-48eb-9ffa-c558930e8446)

L'URL de récupération des données du Comptoir dans le fichier [`/api/src/core/adapters/comptoirDuLibreApi.ts`](https://github.com/codegouvfr/sill/blob/main/api/src/core/adapters/comptoirDuLibreApi.ts#L6) est correcte.

**Comment by dzc34** [comment]
En reprenant l'exemple sur le logiciel Gitlab CE et en regardant le [fichier JSON du SILL](https://code.gouv.fr/sill/api/sill.json) disponible en pied de page de https://code.gouv.fr/sill/ :
- les données à jour du comptoir sont bien présentes dans la propriété `comptoirDuLibreSoftware` de chaque logiciel   ---> 19 prestataires
- en revanche, la propriété `serviceProviders` de chaque logiciel ne semble pas être à jour ---> 17 prestataires

![Screenshot 2024-06-17 at 14-51-06 https __code gouv fr](https://github.com/codegouvfr/sill/assets/6709977/1484a4eb-10bd-4c0c-8e73-d58575b1b1ef)

![Screenshot 2024-06-17 at 14-52-04 https __code gouv fr](https://github.com/codegouvfr/sill/assets/6709977/20963179-b95b-4c54-9e8d-fdc025fd3c53)

**Comment by dzc34** [comment]
> Exemple : [GitLab Community Edition](https://code.gouv.fr/sill/detail?name=GitLab%20Community%20Edition)
> 
> La société Bearstech n'apparaît pas alors qu'elle est bien référencée sur le site Comptoir du Libre : [Bearstech sur Comptoir du Libre](https://comptoir-du-libre.org/fr/softwares/198)

Pour cet exemple là, l'affichage est maintenant correct.

**Comment by bzg** [comment]
Est-ce que le problème remonté a été corrigé?
