### ISSUE TITLE
Impossible d'ajouter une nouvelle instance d'un logiciel

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill#139]
Aller sur https://code.gouv.fr/sill/detail?name=Limesurvey&tab=instances et tenter d'ajouter une instance pour l'organisation "Renater" (non référencée) et pour le public "ESR" : aucune erreur n'est signalée, mais l'instance n'est pas ajoutée et aucune URL n'est demandée pour l'instance.

Je souhaite ajouter https://services.renater.fr/groupware/enquetes/tutoriel pour l'organisation "Renater" et le public "ESR".

**Comment by JeromeBu** [comment]
Comme discuté, en fait le but est de rendre visible les instances privés pour les agents (connecté)

**Comment by JeromeBu** [comment]
voilà ce que ça va donner :

Pour quelqu'un qui n'est pas connecté

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/1e075a21-ef98-44a7-b89e-a9b6406da255">

Pour quelqu'un qui est connecté :

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/ed7d6a58-1acc-49d1-b090-ac34ebf45db8">

**Comment by bzg** [comment]
Parfait, merci. J'ouvre une autre issue pour des corrections de formulations.
