### ISSUE TITLE
Reformulation pour l'affichage des instances

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill#153]
Sur les vues présentées dans [cette issue](https://github.com/codegouvfr/sill/issues/139):

- [ ] Gérer les accords (singuler vs pluriel)
- [ ] Utiliser "instance web" et "instance en accès restreint" au lieu de "publique" et "privée".
- [ ] Possibilité de mettre une URL même pour les instances en accès restreint

**Comment by JeromeBu** [comment]
Je viens de faire en sorte aussi de pouvoir mettre une URL aussi sur une instance privé. On peut l'ajouter à cette issue peut-être ?

**Comment by JeromeBu** [comment]
<img width="1343" alt="image" src="https://github.com/user-attachments/assets/825c220a-f7b6-460b-bd0c-829d980bca47">
