### ISSUE TITLE
Récupération automatique des données de HAL

### ISSUE THREAD

**Issue by guillermau** [codegouvfr/sill#160]
Récupérer automatiquement les données des logiciels venant de la base HAL.

Récupération au lancement et mise à jour régulière.

**Comment by guillermau** [comment]
@JeromeBu penses tu que ce soit d'accord pour autoriser le champ `addedByAgentId` sur la table `softwares` puisse être autoriser à être `null` ?

**Comment by JeromeBu** [comment]
Je te propose qu'on le garde obligatoire, et qu'on crée un agent "Automatisation" (ou un autre nom), avec un email `contact@le-service-qui-bidule.com`. Et puis on le référence dans tous les ajouts automatiques.
