### ISSUE TITLE
Distinguer les applications web et mobile

### ISSUE THREAD

**Issue by ptitloup** [codegouvfr/sill#65]
Bonjour,
Certains services sont proposées via une interface web mais egalement via une application ou son installable (en PWA par exemple).
Est-ce possible sur le SILL de pouvoir le spécifier ? Actuellement on ne peut faire qu'un choix unique
merci

**Comment by garronej** [comment]
Bonjour,  

C'est une bonne remarque.  
Malheureusement, cette modification impliquerais une modification du modèle, ce n'es donc pas un changement qui peut être implémenter rapidement.

**Comment by bzg** [comment]
> Certains services sont proposées via une interface web mais egalement via une application ou son installable (en PWA par exemple).

Aurais-tu des exemples?

Je pense qu'ils entrent dans la catégorie "Logiciels installables sur le poste de travail", même si « l'installation » consiste à télécharger du code JavaScript dans le navigateur, comme pour une PWA.  On pourra reformuler cette question si besoin.

**Comment by ptitloup** [comment]
J'ai pesné à cette fonctionnalié dans le cas du projet Esup-Pod qui est principalement une plateforme web mais avec l'ajout du PWA, on peut maintenant installer la plateforme comme une appli mobile ou desktop.

**Comment by bzg** [comment]
Je ne suis pas sûr de comprendre ce que veut dire "installer la plateforme comme une appli mobile": tu veux dire qu'on installe un client PWA qui se connecte à la plateforme ?  N'hésite pas à m'éclairer, c'est confus pour moi. Merci !

**Comment by ptitloup** [comment]
Grâce à certaines fonctionnalités PWA, le site web peut-etre installé comme une application mobile ou une application système. https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

**Comment by bzg** [comment]
Donc on est bien dans le cas d'un logiciel "installable sur le poste de travail", ce logiciel offrant les mêmes fonctionnalités que le site web.  Pourquoi est-ce que cette catégorie ne conviendrait pas ?

**Comment by ptitloup** [comment]
si cette solution pourrait convenir mais pas en tant que téponse unique, la le probleme n'est pas dans le choix des réponses mais dans le fait qu'elles soient uniques :)

**Comment by bzg** [comment]
Argh... merci !

> Malheureusement, cette modification impliquerais une modification du modèle, ce n'es donc pas un changement qui peut être implémenter rapidement.

@garronej du coup est-ce que ça rend l'implémentation plus facile (même s'il faut encore changer les règles du modèle)?

**Comment by garronej** [comment]
Salut @bzg,  

J'immagine qu'il faudrait distinguer les applications "standalone" comme Gimp et LibreOffice, des applications hébergées dans le cloud qui peuvent avoir des clients web, mobiles ou de bureau.

La tâche n'est pas triviale pour plusieurs raisons :

- Chaque changement de modèle nécessite une migration depuis l'ancien modèle. J'ai déjà prévu des scripts pour cela.
L'interface graphique du SILL est basée sur ce modèle. Lorsque l'on recherche des applications mobiles, l'algorithme les cherche dans une catégorie spécifique. Adapter l'interface et l'algorithme pour que les applications de type "cloud" puissent également avoir des clients lourds nécessiterait des modifications.  

- Cependant, le SILL est "type-safe" de bout en bout. Cela signifie que si l'on modifie quelque chose dans le modèle de base, des erreurs de compilation apparaîtront là où des mises à jour sont nécessaires. C'est donc tout à fait faisable, même pour ceux qui ne sont pas familiers avec la base de code. Il suffit de suivre les erreurs de compilation.  

Je propose que nous prenions une demi-journée pour traiter un certain nombre d'issues ensemble, @bzg et @hjonin. Je pense que vous serez agréablement surpris de voir à quel point il est facile de faire des évolutions une fois que l'environnement de développement est configuré. Pour @bzg, il serait utile que tu aies [le LSP TypeScript pour Emacs](https://vxlabs.com/2022/06/12/typescript-development-with-emacs-tree-sitter-and-lsp-in-2022/), car sans cela, la tâche serait vraiment difficile.

**Comment by bzg** [comment]
Merci pour ta réponse.

Nous n'avons pas besoin de représenter les relations entre des applications en ligne et des clients (web ou mobile) de ces applications - ce serait trop complexe.

Je relance @ptitloup: est-ce que l'application web déployée sur un serveur est _exactement_ ("fonctionnellement") la même que l'application cliente déployée sur web (en PWA) ou mobile?  Ou bien s'agit-il de deux _logiciels_ différents, l'un installé sur un serveur, l'autre installable sur un client?  Peux-tu pointer les liens vers les codes sources pour qu'on comprenne?

Je ne suis toujours pas convaincu qu'il faille changer le modèle pour permettre de choisir plusieurs réponses à la fois.  Je pense qu'il y a deux logiciels : l'un déployé sur un serveur, l'autre déployable sur un client, comme PWA ou autre.  Mais je suis preneur d'infos.

PS: Pour la proposition de prendre du temps sur le SILL, elle est bien notée, on la garde au cas où - merci !

**Comment by ptitloup** [comment]
Je reviens vers vous des que nous sommes passés en production pour vous faire un même de démo. Pour essayer de mieux expliquer, c'est une seule et même application web que l'on peut "installer" sur son smartphone comme une application mobile depuis la page d'accueil

**Comment by bzg** [comment]
Ok, tu nous montreras.  Juste au cas où : je sais ce qu'est une PWA 🙂

**Comment by bzg** [comment]
Je ferme, on n'a pas d'argument fort pour faire évoluer le schéma actuel - @ptitloup n'hésite pas à rouvrir si tu penses le contraire.
