### ISSUE TITLE
Proposer un déploiement avec docker-compose

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill#84]

**Comment by JeromeBu** [comment]
Je pense que ça sera d'autant plus facile une fois passé en monorepo. CF #86

**Comment by bzg** [comment]
Merci pour ton retour !

Il _a été décidé_ de rendre l'application réutilisable en tant que catalogue logiciel générique et nous avons déjà un réutilisateur potentiel (cf. un mail dans ta boîte hier matin.)

Il y a plusieurs dimensions, que je mets par ordre de dépendance:

1. l'architecture fonctionnelle du code
2. les outils de mise en production (aujourd'hui helm et bare)
3. l'organisation des dépôts (aujourd'hui sill-web/api/docs/data)
4. la documentation

Mon hypothèse était qu'on pouvait faire évoluer (2) et (3) sans impact sur (1) et en mettant à jour (4).

Mon autre hypothèse était qu'aller vers du docker-compose prenait 1 jour et passer en monorepo 1 jour aussi.

Je peux être à côté de la plaque sur ces deux hypothèses 🙂

Du coup, j'aurais une question pour @garronej et une autre pour @JeromeBu:

- as-tu un exemple montrant comment l'évolution vers une application générique nous contraint au niveau de la méthode de mise en production et de l'organisation des dépôts ?
- quelle est à la louche ton évaluation sur le temps à prendre pour (2) et (3) ?

Ne partons pas dans une grande discussion dans cette issue: calons un point pour en discuter en janvier, quand @JeromeBu aura de nouveau du temps pour le SILL.

PS: J'ai volonairement laiss de côté le sujet de la base de données, où là on voit clairement la dépendance entre (1) et (3).

**Comment by JeromeBu** [comment]
Pour ce qui est de l'estimation, vraiment je ne connais pas du tout assez le processus de depoilement et CI en place. 
Mais ce que je peux dire c'est que 1 jour + 1 jour me parait beaucoup trop optimiste. S'il y a des process de CI avancé qui font le packaging des images et les déploiement il faudra forcément les reprendre. Il ne s'agit pas simplement de colocaliser les dossiers dans le même repo.
Cela se comptera probablement en semaines... 
Ok pour en discuter en janvier.

**Comment by bzg** [comment]
OK. On continue par mail pour un point en janvier.
