### ISSUE TITLE
Envisager une approche monorepo

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill#86]
Nous avons quatre dépôts: sill-web, [sill-api](https://github.com/codegouvfr/sill-api), [sill-data](https://github.com/codegouvfr/sill-data), [sill-docs](https://github.com/codegouvfr/sill-docs): cela complique le déploiement et la contribution.  Voir si nous devons simplifier et adopter une approche monorepo.

**Comment by garronej** [comment]
I've migrated Onyxia to a Monorepo.  
It could serve as a blueprint.  
https://github.com/InseeFrLab/onyxia  

However I'm sure Gerome has good solutions for this.

**Comment by JeromeBu** [comment]
Je suppose que c'est sill-web qui deviendrait le monorepo ? Ca permettra de conserver les issues déjà existante dans ce repo.

Par contre il faut avoir conscience que ca veut dire qu'on va perdre l'historique de commit des autres repo.

Ca pourrait être l'occasion de le renommer comme mentionné dans l'issue : #85

**Comment by bzg** [comment]
> Je suppose que c'est sill-web qui deviendrait le monorepo ? Ca permettra de conserver les issues déjà existante dans ce repo.

Oui.

> Par contre il faut avoir conscience que ca veut dire qu'on va perdre l'historique de commit des autres repo.

On archivera les autres repos qui ne seront plus utilisés, donc on ne les perdra pas vraiment, c'est juste qu'il ne seront pas dans le monorepo.

(Il y a le sujet de https://github.com/codegouvfr/sill-data qui doit rester privé.)

> Ca pourrait être l'occasion de le renommer comme mentionné dans l'issue : #85

Oui, faisons les propositions de noms dans #85.
