### ISSUE TITLE
Permettre d'ajouter des logiciels depuis HAL

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill#99]

**Comment by bzg** [comment]
Cf. https://github.com/codegouvfr/sill-web/issues/89

**Comment by JeromeBu** [comment]
Permettre de saisir un logiciel à partir d’HAL et mises à jour (via HAL et SWH) - voir https://api.archives-ouvertes.fr/docs/search

**Comment by JeromeBu** [comment]
La plupart du travail se fait coté Sill-api, dans cette PR (en cours) : https://github.com/codegouvfr/sill-api/pull/17
